/********************************************************************
* SBDetectorConstructionCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SBDetectorConstructionCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableSBDetectorConstructionCint();
extern void G__cpp_setup_inheritanceSBDetectorConstructionCint();
extern void G__cpp_setup_typetableSBDetectorConstructionCint();
extern void G__cpp_setup_memvarSBDetectorConstructionCint();
extern void G__cpp_setup_globalSBDetectorConstructionCint();
extern void G__cpp_setup_memfuncSBDetectorConstructionCint();
extern void G__cpp_setup_funcSBDetectorConstructionCint();
extern void G__set_cpp_environmentSBDetectorConstructionCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SBDetectorConstruction.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SBDetectorConstructionCintLN_TClass;
extern G__linked_taginfo G__SBDetectorConstructionCintLN_TBuffer;
extern G__linked_taginfo G__SBDetectorConstructionCintLN_TMemberInspector;
extern G__linked_taginfo G__SBDetectorConstructionCintLN_G4VPhysicalVolume;
extern G__linked_taginfo G__SBDetectorConstructionCintLN_complexlEdoublegR;
extern G__linked_taginfo G__SBDetectorConstructionCintLN_G4String;
extern G__linked_taginfo G__SBDetectorConstructionCintLN_G4VUserDetectorConstruction;
extern G__linked_taginfo G__SBDetectorConstructionCintLN_vectorlEG4VUserParallelWorldmUcOallocatorlEG4VUserParallelWorldmUgRsPgR;
extern G__linked_taginfo G__SBDetectorConstructionCintLN_reverse_iteratorlEvectorlEG4VUserParallelWorldmUcOallocatorlEG4VUserParallelWorldmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SBDetectorConstructionCintLN_G4Tubs;
extern G__linked_taginfo G__SBDetectorConstructionCintLN_G4Polycone;
extern G__linked_taginfo G__SBDetectorConstructionCintLN_G4LogicalVolume;
extern G__linked_taginfo G__SBDetectorConstructionCintLN_G4Material;
extern G__linked_taginfo G__SBDetectorConstructionCintLN_SBDetectorMessenger;
extern G__linked_taginfo G__SBDetectorConstructionCintLN_SBFieldSetup;
extern G__linked_taginfo G__SBDetectorConstructionCintLN_SBDetectorConstruction;

/* STUB derived class for protected member access */
